### ISSUE TITLE
real image edit

### ISSUE THREAD

**Issue by zhw-zhang** [ali-vilab/Ranni#22]
Hi, thank you for your hard work and for open-sourcing this code. It is much appreciated!

I have a question regarding the editing method you have developed. I would like to know if it can be applied to real images. Additionally, do you have any plans to implement this feature in the future?

**Comment by thss15fyt** [comment]
Thanks for your interest. The current version of Ranni does not support real image editing, but focus on continuous image creation. However, it can be extended to incorporate real image understanding that extracts the semantic panel from real image (e.g. bounding boxes from detection). Currently, we do not have plan to implement it.

**Comment by zhw-zhang** [comment]
thanks!
