### ISSUE TITLE
bug on initializing open-clip model

### ISSUE THREAD

**Issue by guyuchao** [ali-vilab/Ranni#3]
In the config, you disable the clip by setting the version to None, So the initializing the clip encounter the following error. How to fix this bug?

cond_stage_config:
      target: ranni.ranni.HackedFrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"
        version: null     # disable loading CLIP here

<img width="944" alt="Screenshot 2024-04-08 at 10 50 00 PM" src="https://github.com/ali-vilab/Ranni/assets/31696690/594969b5-dff0-4d26-b54f-f998573f7035">

**Comment by rivaldophilip** [comment]
@guyuchao could I ask how did you fix this? Encountered the same error 
![image](https://github.com/ali-vilab/Ranni/assets/64348681/acb540b2-61a9-42c5-931b-e582de142cf2)

**Comment by guyuchao** [comment]
change null to '' should fix this problem

**Comment by thss15fyt** [comment]
This is an error caused by the open_clip version. Update it to fix:
`pip install open_clip_torch==2.24.0
`
I will also fix the environment requirements soon.
