### ISSUE TITLE
pip conflict when install the requirements during conda env creation

### ISSUE THREAD

**Issue by holytony** [ali-vilab/Ranni#6]
> ....
> The conflict is caused by:
>     The user requested safetensors==0.2.7
>     transformers 4.30.2 depends on safetensors>=0.3.1
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by thss15fyt** [comment]
Thanks for your reply. We will fix it.

**Comment by thss15fyt** [comment]
You could try to remove the version requirement (`basicsr==1.4.2` -> `basicsr` here) in the `environment.yaml`.

**Comment by holytony** [comment]
still fail to create the environment after basicsr==1.4.2 -> basicsr
> Pip subprocess error:
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [26 lines of output]
>       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
>       Traceback (most recent call last):
>         File "/tmp/pip-install-wu_t02kr/basicsr_6e04e5debf474d2b874ec5c35346b495/setup.py", line 50, in get_hash
>           from basicsr.version import __version__
>         File "/tmp/pip-install-wu_t02kr/basicsr_6e04e5debf474d2b874ec5c35346b495/basicsr/__init__.py", line 3, in <module>
>           from .archs import *
>         File "/tmp/pip-install-wu_t02kr/basicsr_6e04e5debf474d2b874ec5c35346b495/basicsr/archs/__init__.py", line 5, in <module>
>           from basicsr.utils import get_root_logger, scandir
>         File "/tmp/pip-install-wu_t02kr/basicsr_6e04e5debf474d2b874ec5c35346b495/basicsr/utils/__init__.py", line 3, in <module>
>           from .img_process_util import USMSharp, usm_sharp
>         File "/tmp/pip-install-wu_t02kr/basicsr_6e04e5debf474d2b874ec5c35346b495/basicsr/utils/img_process_util.py", line 1, in <module>
>           import cv2
>       ModuleNotFoundError: No module named 'cv2'
>       
>       During handling of the above exception, another exception occurred:
>       
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-wu_t02kr/basicsr_6e04e5debf474d2b874ec5c35346b495/setup.py", line 139, in <module>
>           write_version_py()
>         File "/tmp/pip-install-wu_t02kr/basicsr_6e04e5debf474d2b874ec5c35346b495/setup.py", line 67, in write_version_py
>           sha = get_hash()
>         File "/tmp/pip-install-wu_t02kr/basicsr_6e04e5debf474d2b874ec5c35346b495/setup.py", line 53, in get_hash
>           raise ImportError('Unable to get git version')
>       ImportError: Unable to get git version
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> 
> failed
> 
> CondaEnvException: Pip failed

**Comment by holytony** [comment]
after poking around for a while, turn out this has nothing to do with the project, the error encountered was due to the PyPI mirror I was using just don't have the tb-nightly stuff, after I switch to official source, it's all good

**Comment by DnkNju** [comment]
For anyone encountering this issue when setting up the environment, you can use the following command:
`pip install tb_nightly==2.14.0a20230808 -i https://mirrors.aliyun.com/pypi/simple`
Install tb_nightly first, then proceed to install the other required packages for the project.
