### ISSUE TITLE
Why the box prompt not same as in paper.

### ISSUE THREAD

**Issue by guyuchao** [ali-vilab/Ranni#8]
In the paper, you give the system prompt with detailed illustration of coordinate system and the example. But in this codebase, you remove those contents in the box prompt. Is there any difference in these settings?

<img width="1125" alt="Screenshot 2024-04-09 at 10 02 03 PM" src="https://github.com/ali-vilab/Ranni/assets/31696690/7ac028a3-6e76-4bdf-9f90-cf9f837ba3c4">

**Comment by thss15fyt** [comment]
Yes. We re-train the model with more brief system prompt, and find no obvious performance decreasing. Thus, for efficient inference of demo, we modify it in the released code.

---- Replied Message ----
| From | Yuchao ***@***.***> |
| Date | 04/09/2024 22:05 |
| To | ali-vilab/Ranni ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [ali-vilab/Ranni] Why the box prompt not same as in paper. (Issue #8) |

In the paper, you give the system prompt with detailed illustration of coordinate system and the example. But in this codebase, you remove those contents in the box prompt. Is there any difference in these settings?

Screenshot.2024-04-09.at.10.02.03.PM.png (view on web)
